### ISSUE TITLE
Support for 64-bits

### ISSUE THREAD

**Issue by Dasha-98** [libertyernie/goombasav#1]
Hi,

I'm trying to run the software on a Win 7 64-bit platform.
When starting the program, I'm getting an error saying the app is not compatible with my 64-bit plaform.
I have also tried to use XP compatibility mode without success. So it's really related to x86 vs 64-bit platform.

Any chance to release a 64-bit version of this program ?

I've a workaround but it is quite long...
https://gbatemp.net/threads/goomba-save-manager-export-replace-goomba-sram.364693/#post-6476746

**Comment by libertyernie** [comment]
Can you try this version and let me know if it works?
https://github.com/libertyernie/goombasav/releases/tag/v20160625
If it doesn't work, make sure the VC++ 2015 runtime is installed: https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by Dasha-98** [comment]
Program is now launching.
I've installed VC++ 2015 but had to install the x86 version. I first installed 64-bit version only and still a dll was missing.
Thanks for your support.
