### ISSUE TITLE
.NET Version?

### ISSUE THREAD

**Issue by NikeLaosClericus** [libertyernie/goombasav#11]
The application warns me on launch that I need .NET Core, but when I click Yes to download, it does nothing...

Can I just directly install the correct version of the .NET SDK?

**Comment by NikeLaosClericus** [comment]
Found it, .NET 3.1.
Manually installing the SDK worked.

**Comment by 0xcircuitbreaker** [comment]
I tried using .NET 3,1 yet I am still facing the popup regarding .NET Core
