### ISSUE TITLE
Error : "Array length is smaller than 65536 bytes"

### ISSUE THREAD

**Issue by Dasha-98** [libertyernie/goombasav#2]
Hi,

I tried to load a save file.
When I select it, I get the error "Array length is smaller than 65536 bytes".

I attached to the file to the ticket.
The file is generated from SuperCard SD integrated emulator (firmware 1.85, the latest).
The file is readable in TGB Dual 1.21 (which is using Goomba Save Manager code).

**Comment by Dasha-98** [comment]
[Pokemon Version Rouge (FR).zip](https://github.com/libertyernie/goombasav/files/337761/Pokemon.Version.Rouge.FR.zip)

**Comment by libertyernie** [comment]
I see the problem - goombasav expects a file to be 64 KB and that's only 32 KB. I'll take out the minimum filesize limit. (TGB Dual always feeds goombasav a 64 KB file internally.)

**Comment by Dasha-98** [comment]
Hi,

Indeed. TGB Dual created a 64kb file (compared to the original 32kb file used by Goomba).

The file created by TGB Dual can be read by Goomba Save Manager.

**Comment by libertyernie** [comment]
I posted a new version that can load 32KB files or smaller.
Do the 64KB files work in SuperCard SD? If so, I'll close this issue.

**Comment by Dasha-98** [comment]
I don't see new version, only the 25th June one.
If you route me to it, I'll retest.

Yes, 64kb files are working on SuperCard SD.

**Comment by libertyernie** [comment]
Oops. Just uploaded it.
https://github.com/libertyernie/goombasav/releases/tag/v20160628

**Comment by Dasha-98** [comment]
Thanks, I'll test this evening and close the issue.

**Comment by Dasha-98** [comment]
This issue is now solved with your latest release.
Thanks.
