### ISSUE TITLE
How to use the sav file?

### ISSUE THREAD

**Issue by applefreak** [libertyernie/goombasav#3]
Sorry if this is not the right place to ask, but I would like to know how to use the sav file extracted with `goombasav_cs.exe`, I got an 8kb sav file. Which emulator is compatible with this type of sav file on PC?

Thanks!

Edit: The game is Pokemon Yellow

**Comment by libertyernie** [comment]
You should be able to use it with pretty much any GBC emulator. I know VBA-M and TGB Dual will read it.

**Comment by applefreak** [comment]
I think I know my problem. Initially I was asking because I can't seem to load the SRAM. I only get `New Game` option in Pokemon. It's because that Goomba is not saving SRAM for some reason. I've been using Goomba's save state function without a problem though.

Thanks anyway! If you got any pointer please tell me about it!

Edit: I'm not using Goomba Color, maybe it has to do with Goomba's save file size?

**Comment by libertyernie** [comment]
I think there is a problem in Goomba with games that have a lot of sram,
like pokemon. I use Goomba Color for those.

**Comment by applefreak** [comment]
Hmm, OK. Do you know anyway to extract the save states then? I'm already half way into the game. Because I want to extract the save so I can load it to my Gameboy flash cart that I'm getting.

**Comment by libertyernie** [comment]
Maybe you can get it by running the GBA ROM in an emulator and extracting the GBA RAM into a file - I think an uncompressed copy of the GB save file is in there somewhere.

I thought I saw a thread on gbatemp about this once but now I can't find it.

**Comment by applefreak** [comment]
I tried running it in GBA-M but all I got is a white screen when loading
the compiled Goomba .gba, I'll try it in different emulator and see how it
goes.

Thank you!

**Comment by applefreak** [comment]
Hello, I got my Goomba ROM working in VBA-M. I can successfully load savestate from my save file, but still SRAM doesn't work. I think the only way for me is to extract the raw save from the GBA RAM like you said.

So do you know where the memory offset it's at?

Thanks!

**Comment by applefreak** [comment]
Good new!! I found the address myself!

The memory location is at: `0x02038000`! Size 8000

I found it [here](http://www.dwedit.org/dwedit_board/viewtopic.php?id=663)!

Feel free to close this issue now. Thank you for your time and this great tool you wrote!
