### ISSUE TITLE
Support for Savestate extraction/insertion?

### ISSUE THREAD

**Issue by KuestenKeks** [libertyernie/goombasav#6]
I wondered if savestate extraction / insertion would be possible to implement?

I guess it's much more interesting for most people to manage the SRAM saves. But at least for me managing savestates would also be great x)

There are a few Game Boy games where saving isn't possible and you loose your progress and high scores when powering off the game. Like Wizards & Warriors and especially Tetris. I've been been playing Tetris for over 10 years now with Goomba and savestates enabled me to keep my own and also my friends high scores during all those years :)

Now I would like to move away from the old Goomba version on my old GBA flash cart. I was hoping to be able to insert my savestates into a fresh Goomba save on an Everdrive x5.

Do you think savestate support would be possible at all to implement, libertyernie? What are your thoughts on this?

**Comment by libertyernie** [comment]
See if the new release (https://github.com/libertyernie/goombasav/releases/tag/v20210112) solves this problem (and the other one you filed - figured I'd take care of both at once if possible).

**Comment by KuestenKeks** [comment]
wow, thanks @libertyernie !

Unfortunately it doesn't work with the latest Goomba release by Dwedit (Version 2019-05-04):

- Extracting a savestate throws an error: `Cannot decompress data (lzoconf.h error code -6).`
- Extracting a savestate from my 10 year old Goomba did not throw an error, neither did injecting it into the new Goomba save. But when starting up the new Goomba I can't load the injected savestate. It shows up in the savestate menu, but nothing at all happens when I load the savestate.

SRAM replacing seems to work fine though :)

One more thing: drag and drop with the GUI doesn't work for me. An error window pops up with the message "No item is selected." I tried to drop a GBA .sav file.

btw, do you accept donations?

**Comment by libertyernie** [comment]
Mind posting a link where I can download a .sav file from a newer goomba? (I suppose it's also possible that they changed the savestate format between then and now, in which case there's not much this program could do.)

I don't have a donation link - I already make money doing programming so I figure I'm good 👍 

By the way - the "no item is selected" message shows up because GOOMBA_STATEID is set to 0x0x57a731d8, but both Goomba and Goomba Color seem to use 0x57a731dc instead. Not sure if that's a old/new difference too or what. But the GUI should really accept both.

**Comment by KuestenKeks** [comment]
This Goomba save contains a Tetris savestate and a Super Mario Land 2 SRAM save:
https://share.anoxinon.de/f.php?h=3ZZl3RWGZWP75HUhYa4wnB&d=1

Edit: Same error with Goomba Color 12_14_2014. I'll try to test more versions during the next days, maybe I can find out which Goomba version introduced the savestate changes.

**Comment by KuestenKeks** [comment]
Well.. I've looked into the older Goomba Color releases by Dwedit. And the first one that had working savestates is 12-14-2014. All previous releases mention the following in their readme: "Savestates are broken, therefore DISABLED in this version."

I guess savestate implementation differs between Goomba Classic and Goomba Color. Probably makes sense as the original/classic Game Boy and the Game Boy Color are different handhelds with different specs? And your implementation only supports Goomba Classic for now.

What I was trying to do probably wouldn't have worked anyway: Importing savestates from Goomba Classic into Goomba Color.

Anyway, cheers and kind regards :)
